defaults:
  - task: splice
  - model: giga
  - runtime: local
  - experiment: splice_prepare_only
  - callbacks: default
  - logging: default
  - _self_

dry_run: true

hydra:
  job:
    chdir: false
  run:
    dir: .
